--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GalaxyGamesMC/Ovommand
build-by-default: true
branches:
- main
projects:
  Ovommand:
    path: ""
    model: virion
    type: library
...
