--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GalaxyGamesMC/Ovommand
branches:
- main
projects:
  Ovommand:
    model: virion
    type: library
    lint:
      phpstan: true
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.5
...